sonar.organization=appcraft008-dev
sonar.projectKey=appcraft008-dev_GoMuseum
sonar.projectName=GoMuseum
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.venv/**,**/coverage/**,**/dist/**,**/build/**
sonar.sourceEncoding=UTF-8
sonar.tests=backend/tests,frontend/test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.python.coverage.reportPaths=backend/coverage.xml

