"""
Explanation Database Models
SQLAlchemy ORM models for artwork explanations and TTS audio
"""

from sqlalchemy import Column, String, Text, DateTime, ForeignKey, Integer, Index, func
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
import uuid

from app.core.database import Base


class Explanation(Base):
    """
    Artwork explanation content table
    Stores multi-language explanations generated by AI
    """

    __tablename__ = "explanations"

    # Primary key and foreign key
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    recognition_id = Column(
        UUID(as_uuid=True), ForeignKey("recognition_results.id"), nullable=True
    )

    # Core fields
    artwork_name = Column(String(255), nullable=False, index=True)
    language = Column(String(10), nullable=False, index=True)  # en, fr, de, es, it, zh

    # Content fields
    content = Column(Text, nullable=False)
    meta_info = Column(JSONB, default={})  # Extended fields: generation params, version

    # Audio association
    audio_url = Column(String(512), nullable=True)
    audio_duration_seconds = Column(Integer, nullable=True)

    # Metadata
    timestamp = Column(DateTime, server_default=func.now(), nullable=False)
    content_hash = Column(String(64), index=True)  # For deduplication

    # Relationships
    recognition = relationship("RecognitionResult", back_populates="explanations")

    # Composite indexes: artwork_name + language is common query pattern
    __table_args__ = (
        Index("ix_explanation_artwork_lang", "artwork_name", "language", unique=True),
        Index("ix_explanation_hash", "content_hash"),
        Index("ix_explanation_timestamp", "timestamp"),
    )

    def __repr__(self):
        return f"<Explanation(artwork={self.artwork_name}, lang={self.language})>"


class ExplanationAudio(Base):
    """
    TTS audio metadata table (optional, for independent audio management)
    Stores metadata about generated audio files
    """

    __tablename__ = "explanation_audios"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    explanation_id = Column(UUID(as_uuid=True), ForeignKey("explanations.id"))

    # Audio file information
    audio_url = Column(String(512), nullable=False)
    file_path = Column(String(512), nullable=False)  # Local storage path
    file_size_bytes = Column(Integer)
    duration_seconds = Column(Integer)

    # TTS parameters
    voice = Column(String(50), default="alloy")
    model = Column(String(50), default="tts-1")
    speed = Column(Integer, default=100)  # Speed in percentage (100 = 1.0x)

    # Metadata
    created_at = Column(DateTime, server_default=func.now())
    expires_at = Column(DateTime)  # Audio expiration time

    # Relationships
    explanation = relationship("Explanation", backref="audios")

    def __repr__(self):
        return f"<ExplanationAudio(id={self.id}, voice={self.voice})>"
