"""step1 data foundation

Revision ID: d6ca257376ac
Revises: 009_user_benefits_and_cleanup
Create Date: 2026-06-14 18:39:57.684196

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6ca257376ac"
down_revision: Union[str, None] = "009_user_benefits_and_cleanup"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "museums",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("qid", sa.String(length=32), nullable=True),
        sa.Column("name_zh", sa.String(length=255), nullable=True),
        sa.Column("name_en", sa.String(length=255), nullable=True),
        sa.Column("city_zh", sa.String(length=128), nullable=True),
        sa.Column("city_en", sa.String(length=128), nullable=True),
        sa.Column("country", sa.String(length=8), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_museums_slug"), "museums", ["slug"], unique=True)
    op.create_table(
        "section_types",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("label_zh", sa.String(length=64), nullable=True),
        sa.Column("label_en", sa.String(length=64), nullable=True),
        sa.Column("icon", sa.String(length=64), nullable=True),
        sa.Column("default_sort", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "category_sections",
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("section_code", sa.String(length=32), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["section_code"],
            ["section_types.code"],
            name="fk_category_sections_section_code",
        ),
        sa.PrimaryKeyConstraint("category", "section_code"),
    )
    op.create_table(
        "museum_objects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("museum_id", sa.UUID(), nullable=False),
        sa.Column("qid", sa.String(length=32), nullable=True),
        sa.Column("inventory_number", sa.String(length=128), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("title_zh", sa.String(length=512), nullable=True),
        sa.Column("title_en", sa.String(length=512), nullable=True),
        sa.Column("artist_zh", sa.String(length=255), nullable=True),
        sa.Column("artist_en", sa.String(length=255), nullable=True),
        sa.Column("year", sa.String(length=64), nullable=True),
        sa.Column("period_zh", sa.String(length=128), nullable=True),
        sa.Column("period_en", sa.String(length=128), nullable=True),
        sa.Column("popularity", sa.Integer(), nullable=True),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["museum_id"], ["museums.id"], name="fk_museum_objects_museum_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "museum_id", "inventory_number", name="uq_object_museum_inventory"
        ),
    )
    op.create_index(
        op.f("ix_museum_objects_museum_id"),
        "museum_objects",
        ["museum_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_museum_objects_popularity"),
        "museum_objects",
        ["popularity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_museum_objects_qid"), "museum_objects", ["qid"], unique=True
    )
    op.create_table(
        "object_content_sections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("object_id", sa.UUID(), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("section_code", sa.String(length=32), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("audio_key", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=True),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=True),
        sa.Column("generated_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["object_id"],
            ["museum_objects.id"],
            name="fk_object_content_sections_object_id",
        ),
        sa.ForeignKeyConstraint(
            ["section_code"],
            ["section_types.code"],
            name="fk_object_content_sections_section_code",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "object_id", "language", "section_code", name="uq_content_obj_lang_section"
        ),
    )
    op.create_index(
        op.f("ix_object_content_sections_object_id"),
        "object_content_sections",
        ["object_id"],
        unique=False,
    )
    op.create_table(
        "object_images",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("object_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("image_key", sa.Text(), nullable=True),
        sa.Column("license", sa.String(length=128), nullable=True),
        sa.Column("credit", sa.String(length=255), nullable=True),
        sa.Column("sort", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["object_id"], ["museum_objects.id"], name="fk_object_images_object_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_object_images_object_id"), "object_images", ["object_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_object_images_object_id"), table_name="object_images")
    op.drop_table("object_images")
    op.drop_index(
        op.f("ix_object_content_sections_object_id"),
        table_name="object_content_sections",
    )
    op.drop_table("object_content_sections")
    op.drop_index(op.f("ix_museum_objects_qid"), table_name="museum_objects")
    op.drop_index(op.f("ix_museum_objects_popularity"), table_name="museum_objects")
    op.drop_index(op.f("ix_museum_objects_museum_id"), table_name="museum_objects")
    op.drop_table("museum_objects")
    op.drop_table("category_sections")
    op.drop_table("section_types")
    op.drop_index(op.f("ix_museums_slug"), table_name="museums")
    op.drop_table("museums")
    # ### end Alembic commands ###
